### ISSUE TITLE
Open API 2.0 and unsupported content types in OpenAPI 3.0

### ISSUE THREAD

**Issue by jumic** [taimos/cdk-serverless#118]
Hi Thorsten,

I have some feedback after I started doing a small demo project with cdk-serverless.
Could you please check my findings? From my point of view, it's possible solve them in the coding (add support or display errors/warnings) or just mention it in the documentation.

#### Do you want to request a feature or report a bug?
bug

##### 1) OpenAPI in version 2.0 (swagger) #####
I started with the OpenAPI definition which is provided as an example if you open https://editor.swagger.io/ the first time.

In the generated Lambda function, requests with body will show this error:
```
Type '{ parameters: { body: { body: { id?: number | undefined; category?: { id?: number | undefined; name?: string | undefined; } | undefined; name: string; photoUrls: string[]; tags?: { id?: number | undefined; name?: string | undefined; }[] | undefined; status?: "available" | ... 2 more ... | undefined; }; }; }; respons...' does not satisfy the constraint 'OperationWithRequestBody'.
Property 'requestBody' is missing in type '{ parameters: { body: { body: { id?: number | undefined; category?: { id?: number | undefined; name?: string | undefined; } | undefined; name: string; photoUrls: string[]; tags?: { id?: number | undefined; name?: string | undefined; }[] | undefined; status?: "available" | ... 2 more ... | undefined; }; }; }; respons...' but required in type 'OperationWithRequestBody'.ts(2344)
```
The Open API file uses version `swagger: "2.0"` where keyword `requestBody` is missing. After I converted the openapi.yaml to OpenAPI 3.0, the error disappeared.

Suggested options:
1. Add to documentation: Only OpenAPI 3.0 and above is supported. Maybe check OpenAPI version in the generator and throw an error if an unsupported version is used.
2. Solve underlying issue.

##### 2. Content type `*/*` not supported #####
The example API definition from https://editor.swagger.io/ uses content type `*/*` instead of `application/json`. This leads to the following error in the generated Lambda function:
```
Type '{ responses: { default: unknown; }; requestBody: { content: { "*/*": { id?: number | undefined; username?: string | undefined; firstName?: string | undefined; lastName?: string | undefined; email?: string | undefined; password?: string | undefined; phone?: string | undefined; userStatus?: number | undefined; }; }; }...' does not satisfy the constraint 'OperationWithRequestBody'.
  The types of 'requestBody.content' are incompatible between these types.
Property ''application/json'' is missing in type '{ "*/*": { id?: number | undefined; username?: string | undefined; firstName?: string | undefined; lastName?: string | undefined; email?: string | undefined; password?: string | undefined; phone?: string | undefined; userStatus?: number | undefined; }; }' but required in type '{ 'application/json': any; }'.ts(2344)
```

Caused by this API method:
```
requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
```

Suggested options:
1. Add to documentation: Only content type `application/json` is supported in the request body.
2. Solve underlying issue.

##### 3. Content type `application/x-www-form-urlencoded` not supported #####
Similar to problem 2: Content type application/x-www-form-urlencoded is not supported.
```
Type '{ parameters: { path: { petId: number; }; }; responses: { 405: unknown; }; requestBody: { content: { "application/x-www-form-urlencoded": { name?: string | undefined; status?: string | undefined; }; }; }; }' does not satisfy the constraint 'OperationWithRequestBody'.
  The types of 'requestBody.content' are incompatible between these types.
    Property ''application/json'' is missing in type '{ "application/x-www-form-urlencoded": { name?: string | undefined; status?: string | undefined; }; }' but required in type '{ 'application/json': any; }'.ts(2344)
```
Caused by this API method:

```
requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
```

##### 4. Content type `multipart/form-data` not supported #####
Similar to problem 2: Content type multipart/form-data is not supported.
```
Type '{ parameters: { path: { petId: number; }; }; responses: { 200: { content: { "application/json": { code?: number | undefined; type?: string | undefined; message?: string | undefined; }; }; }; }; requestBody: { ...; }; }' does not satisfy the constraint 'OperationWithRequestBody'.
  The types of 'requestBody.content' are incompatible between these types.
    Property ''application/json'' is missing in type '{ "multipart/form-data": { additionalMetadata?: string | undefined; file?: string | undefined; }; }' but required in type '{ 'application/json': any; }'.ts(2344)
```

Caused by this API method:
```
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
```

#### If the current behavior is a bug, please provide the steps to reproduce it.
Import API definition from https://editor.swagger.io/ and execute `projen generate:api`. Next, open the generated lambda coding in the IDE to see the errors.

For tests with OpenAPI 3, convert the file from https://editor.swagger.io/ using Edit --> Convert to OpenAPI 3 in the online editor.

#### What is the expected behavior?
No error messages displayed in the IDE for the generated coding.

#### Which versions of CDK Serverless are affected by this issue? Did this work in previous versions?
cdk-serverless version 0.1.42

#### Additional remarks
For me, it's not necessary to add those functions to cdk-serverless. It would be sufficient to describe those limitations in the readme. If you agree to it, I can add it to the readme and create a pull request.

I would also suggest to link the [openapi.yaml file from your demo project](https://github.com/taimos/cdk-serverless-demo-http/blob/main/openapi.yaml) in  the quick start section to provide a fully supported OpenAPI definition as an example.

**Comment by hoegertn** [comment]
Hi,

thanks for the detailled report. I would like to set a minimum of OpenAPI 3.

In the future, I would love to support multiple content types but for the time being it is limited to json as the generics might get out of hand otherwise.

If you create a PR to put this into the README I would love to merge this.
