### ISSUE TITLE
Support authentication in HttpApi 

### ISSUE THREAD

**Issue by jumic** [taimos/cdk-serverless#119]
#### Do you want to request a feature or report a bug?
feature

#### What is the current behavior?
The HttpApi generates an API Gateway (v2), all API methods are accessible without authentication.

#### What is the expected behavior?
If enabled, API methods can be defined as protected. Access is only possible for users defined in the Cognito User Pool.

#### Suggested implementation
It's necessary to create an App Client in the Cognito User Pool.
- For existing authentication, I would add a new property in `IAuthentication` to pass an existing App Client.
- If the User Pool is generated in HttpApi, I would add the necessary configuration to `AuthenticationProps`.

Using the User Pool and the App Client, I would create an HttpUserPoolAuthorizer and attach it to each `apiGw.HttpRoute` which is created in method `addCustomRoute()`.

How to configure which API methods should be protected? In the OpenAPI definition, a protected API method can be defined using keyword `security`. If this keyword is set, I would propose to add the HttpUserPoolAuthorizer to the API method. This approach provides the advantage, that no additional configuration is necessary to specify which API methods should be protected.

Please let me know if I can implement the feature and create a pull request. If you have some optimizations, please let me know, too.

**Comment by hoegertn** [comment]
Hi, thanks for this finding.

When I started using APi GW v2 Authorizer support was very limited so I fell back to doing auth inside the Lambda function. This is what happens in the Lambda toolbox right now. But if we can add authorizers in API GW v2 directly for Cognito this would improve security I think.

I would love to see a PR with this change.
